export { default as Cart } from './Cart'
export { default as Filters } from './Filters'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Pagination } from './Pagination'
export { default as Products } from './Products'
